# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  weight: 1

# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr
  contentDir: content/fr
  weight: 2
  title: "Thibault Genissel - Recherche"
  params:
    description: "Mon CV académique et mes publications"
  menu:
    main:
      - name: Bio
        url: /fr/
        weight: 10



      - name: CV
        url: /fr/experience/
        weight: 20   

      - name: Recherche
        url: /fr/concepts/     
        weight: 30

      - name: Publications
        url: /fr/publications/
        weight: 40

      - name: Conférences
        url: /fr/book/
        weight: 50

      - name: Profil conférencier
        url: /fr/speaker/
        weight: 45
  #    - name: Projets
   #     url: /fr/project/
    #    weight: 60
      - name: Galerie
        url: /fr/gallery/
        weight: 70
